import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const moduleUrl = code => 'data:text/javascript;base64,' + Buffer.from(code).toString('base64');
const compile = path => ts.transpileModule(readFileSync(path, 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const mockTmdb = moduleUrl(`export const CACHE={hour:3600}; export const jsonOk=(data,status=200)=>({data,status}); export const jsonErr=(error,status)=>({error,status}); export const jsonFromError=error=>({error,status:500}); export const tmdbFetch=(...args)=>globalThis.fetchTitles(...args);`);
await import('./test-feed-resilience.mjs');
const params=moduleUrl('export const buildParams=()=>({});');
const discover=await import(moduleUrl(compile('src/app/api/getDiscover/route.ts').replace('"@/lib/tmdb"',JSON.stringify(mockTmdb)).replace('"@/lib/discover-params"',JSON.stringify(params))));
globalThis.fetchTitles=async()=>({results:[{id:42,name:'A series'}],page:2,total_pages:7,total_results:132});
const tv=await discover.GET(new Request('https://supawatch.test/api/getDiscover?type=tv&page=2'));
assert.equal(tv.data.results[0].media_type,'tv');
assert.equal(tv.data.page,2);assert.equal(tv.data.total_pages,7);assert.equal(tv.data.total_results,132);
console.log('PASS discover retains TV identity and pagination metadata');
// Mixed discovery keeps both identities and enough pagination to reach either catalogue.
const mixed=await discover.GET(new Request('https://supawatch.test/api/getDiscover?type=mixed&page=2'));
assert.equal(mixed.data.results.length,2);
assert.deepEqual(new Set(mixed.data.results.map(item=>item.media_type)),new Set(['movie','tv']));
assert.equal(mixed.data.total_pages,7);assert.equal(mixed.data.total_results,264);
globalThis.fetchTitles=async()=>{throw Error('Offline');};
assert.equal((await discover.GET(new Request('https://supawatch.test/api/getDiscover?type=mixed'))).status,503);
console.log('PASS mixed discovery preserves pagination and reports upstream failure');
const searchTmdb=moduleUrl(`export const CACHE={fiveMinutes:300,hour:3600}; export const jsonOk=(data,status=200)=>({data,status}); export const jsonErr=(error,status)=>({error,status}); export const jsonFromError=error=>({error,status:500}); export const sanitizePage=value=>String(Math.max(1,Number(value)||1)); export const tmdbFetch=(...args)=>globalThis.fetchTitles(...args);`);
const search=await import(moduleUrl(compile('src/app/api/getSearch/route.ts').replace('"@/lib/tmdb"',JSON.stringify(searchTmdb)).replace('"@/lib/search-filters"',JSON.stringify(moduleUrl(compile('src/lib/search-filters.ts'))))));
let searchCall;
globalThis.fetchTitles=async(endpoint,params)=>{searchCall={endpoint,params};return {page:2,total_pages:4,results:[{id:1396,name:'Breaking Bad'}]};};
const typedSearch=await search.GET(new Request('https://supawatch.test/api/getSearch?query=%20Breaking%20Bad%20&type=tv&page=2'));
assert.equal(searchCall.endpoint,'/search/tv');assert.equal(searchCall.params.query,'Breaking Bad');assert.equal(searchCall.params.page,2);
assert.equal(typedSearch.data.data.results[0].media_type,'tv');assert.equal(typedSearch.data.data.total_pages,4);
assert.equal((await search.GET(new Request('https://supawatch.test/api/getSearch?query=title&type=invalid'))).status,400);
console.log('PASS format-specific search uses the correct endpoint and preserves TV identity');
